import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'

import Link from 'next/link';

import styles from '../styles/Home.module.css'
import heroBackground from '../public/dfw.jpg'
import heroOverlay from '../public/overlay.png'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav className="navbar p-3">
      <div className="nav-top flex justify-between items-center px-2"><a className="logo font-thin w-1/6" href="/"><div className="text-xl leading-tight uppercase"><span className="text-3xl font-black">T</span><span className="logo__hidden inline-block text-lime-dark">ravis</span><span className="text-3xl font-black">H</span><span className="logo__hidden inline-block text-lime-dark">arvey</span></div></a><div className=""><ul className="flex justify-center items-center"><li><a className="uppercase text-lime-dark font-thin text-base hover:text-lime-light mx-2" href="/about">About</a></li><li><a className="uppercase text-lime-dark font-thin text-base hover:text-lime-light mx-2" href="/portfolio">Portfolio</a></li></ul></div></div>
      </nav>
      <main className="overflow-hidden">
        Contact
      </main>
    </>
  )
}
